wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.4
    framework: huggingface
    huggingface_version: 4.22.1
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.10.4
    start_time: 1680279920.035903
    t:
      1:
      - 1
      - 5
      - 11
      - 33
      - 41
      - 49
      - 51
      - 53
      - 55
      - 71
      - 75
      2:
      - 1
      - 5
      - 11
      - 33
      - 41
      - 49
      - 51
      - 53
      - 55
      - 71
      - 75
      3:
      - 23
      4: 3.10.4
      5: 0.13.4
      6: 4.22.1
      8:
      - 5
adam_beta1:
  desc: null
  value: 0.9
adam_beta2:
  desc: null
  value: 0.999
adam_weight_decay:
  desc: null
  value: 1.0e-06
amp:
  desc: null
  value: false
beta_schedule:
  desc: null
  value: linear
class_conditional:
  desc: null
  value: false
class_unconditional_prob:
  desc: null
  value: 0.1
corruption_prob:
  desc: null
  value: 0.0
dataset_name:
  desc: null
  value: roc
ddim_sampling_eta:
  desc: null
  value: 1
disable_dropout:
  desc: null
  value: true
ema_decay:
  desc: null
  value: 0.9999
ema_update_every:
  desc: null
  value: 1
enc_dec_model:
  desc: null
  value: facebook/bart-base
eval:
  desc: null
  value: false
eval_batch_size:
  desc: null
  value: 32
eval_test:
  desc: null
  value: false
gen_data:
  desc: null
  value: false
gradient_accumulation_steps:
  desc: null
  value: 1
learning_rate:
  desc: null
  value: 0.0001
loss_type:
  desc: null
  value: l1
lr_schedule:
  desc: null
  value: cosine
lr_warmup_steps:
  desc: null
  value: 1000
milestone:
  desc: null
  value: 12
mixed_precision:
  desc: null
  value: 'no'
normalize_latent:
  desc: null
  value: true
num_samples:
  desc: null
  value: 1000
num_train_steps:
  desc: null
  value: 500000
objective:
  desc: null
  value: pred_x0
output_dir:
  desc: null
  value: saved_models/roc/2023-03-31_16-25-13
p2_loss_weight_gamma:
  desc: null
  value: 0
resume_dir:
  desc: null
  value: null
resume_training:
  desc: null
  value: false
sampling_timesteps:
  desc: null
  value: 250
save_and_sample_every:
  desc: null
  value: 5000
save_dir:
  desc: null
  value: saved_models
scale_shift:
  desc: null
  value: true
self_condition:
  desc: null
  value: true
timesteps:
  desc: null
  value: 1000
train_batch_size:
  desc: null
  value: 64
trainable_params:
  desc: null
  value: 214342272
tx_depth:
  desc: null
  value: 12
tx_dim:
  desc: null
  value: 768
wandb_name:
  desc: null
  value: null
